version: '3.8'

services:
  local-llama:
    build: ./
    ports:
      - '3000:3000'
    volumes:
    - /home/ubuntu/local-ai:/app/local-ai # 호스트 디렉토리를 컨테이너로 마운트

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - local-llama
